spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a214
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR